server:
  port: 8090
spring:
  application:
    name: admin-server

  ###################
  # 邮件通知配置 此处暂时注释掉，如果要运行的话请先配置好，否此控制台会报错
  ##################
#  mail:
#    host: smtphm.qiye.163.com
#    username: # 用户名
#    password: # 密码
#  boot:
#    admin:
#      notify:
#        mail:
#          to: # 收件人
#          enabled: true
#          from: # 发件人


eureka:
  instance:
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health
      prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://123.207.98.252:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS