server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://123.207.98.252:3306/any?serverTimezone=Asia/Shanghai&amp;useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
