server:
  port: 8761
  servlet:
    context-path: / #统一为访问的url加上一个前缀

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/eureka/

spring:
  application:
    name: eurka