server:
  port: 8081
  servlet:
    context-path: /eureka #统一为访问的url加上一个前缀

eureka:
  instance:
    hostname: 123.207.98.252
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://123.207.98.252:8081/eureka/eureka/

spring:
  application:
    name: eurka