server:
  port: 8761

eureka:
  instance:
    hostname: 123.207.98.252
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://123.207.98.252:8761/eureka/

spring:
  application:
    name: eurka-server
  security:
    user:
      name: admin
      password: 123123
